apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solar-system.fullname" . }}
  labels:
    {{- include "solar-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "solar-system.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "solar-system.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "solar-system.fullname" .) }}
      containers:
        - name: solar-system
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_URI
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_PASSWORD
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
