apiVersion: v1
kind: Service
metadata:
  name: {{ include "solar-system.fullname" . }}
  labels:
    {{- include "solar-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "solar-system.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
